In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3600, 3346, 4074, 6026],
 [3600, 3346, 4074, 6611],
 [3600, 2273, 4074, 4734],
 [9005, 8766, 8347, 6673, 8783],
 [9005, 8766, 8347, 6673, 9278],
 [6721, 3600, 3843, 4074, 7178],
 [5891, 6007, 2202, 6673]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3600 3346 4074 6026]
 [   0    0    0    0 3600 3346 4074 6611]
 [   0    0    0    0 3600 2273 4074 4734]
 [   0    0    0 9005 8766 8347 6673 8783]
 [   0    0    0 9005 8766 8347 6673 9278]
 [   0    0    0 6721 3600 3843 4074 7178]
 [   0    0    0    0 5891 6007 2202 6673]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 71ms/step


array([[[ 0.03594032, -0.00140449,  0.04790543,  0.01995395,
          0.02465483,  0.02141089, -0.02230814, -0.03100373,
         -0.03669954,  0.00337338],
        [ 0.03594032, -0.00140449,  0.04790543,  0.01995395,
          0.02465483,  0.02141089, -0.02230814, -0.03100373,
         -0.03669954,  0.00337338],
        [ 0.03594032, -0.00140449,  0.04790543,  0.01995395,
          0.02465483,  0.02141089, -0.02230814, -0.03100373,
         -0.03669954,  0.00337338],
        [ 0.03594032, -0.00140449,  0.04790543,  0.01995395,
          0.02465483,  0.02141089, -0.02230814, -0.03100373,
         -0.03669954,  0.00337338],
        [ 0.03510863,  0.04610914, -0.04754756,  0.02492725,
          0.03748006, -0.04261882,  0.00966638,  0.03382182,
          0.02897904, -0.03561834],
        [ 0.04221473, -0.02093887, -0.00870639,  0.03158815,
         -0.01079031, -0.0374909 ,  0.03349009,  0.00808798,
         -0.03812758, -0.01137887],
        [-0.02217914,  0.03780563, -0.0184889 ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3600, 3346, 4074, 6026], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.03594032, -0.00140449,  0.04790543,  0.01995395,  0.02465483,
         0.02141089, -0.02230814, -0.03100373, -0.03669954,  0.00337338],
       [ 0.03594032, -0.00140449,  0.04790543,  0.01995395,  0.02465483,
         0.02141089, -0.02230814, -0.03100373, -0.03669954,  0.00337338],
       [ 0.03594032, -0.00140449,  0.04790543,  0.01995395,  0.02465483,
         0.02141089, -0.02230814, -0.03100373, -0.03669954,  0.00337338],
       [ 0.03594032, -0.00140449,  0.04790543,  0.01995395,  0.02465483,
         0.02141089, -0.02230814, -0.03100373, -0.03669954,  0.00337338],
       [ 0.03510863,  0.04610914, -0.04754756,  0.02492725,  0.03748006,
        -0.04261882,  0.00966638,  0.03382182,  0.02897904, -0.03561834],
       [ 0.04221473, -0.02093887, -0.00870639,  0.03158815, -0.01079031,
        -0.0374909 ,  0.03349009,  0.00808798, -0.03812758, -0.01137887],
       [-0.02217914,  0.03780563, -0.0184889 ,  0.04044391,  0.00776957,
         0.00452814,  0.03716281, -0.00828727